### PR TITLE
Better memory layout, more vectorization, Numba

### PR DESCRIPTION
**Pull request by 99991**
I made a few additional experiments:

- I stored the polygon vertices sequentially in memory, which allows for full vectorization with NumPy. This made things faster, but still slower than Rust.
- I tested JIT compilation with [Numba](https://numba.pydata.org/). This was faster faster than the Rust implementation.
- I again tested Numba, but this time I discarded polygons early if the center was so far away that no vertex can possibly be within range of the query point. This was much faster.

I'd also like to mention the [KDTree data structure](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.KDTree.html) which supports ball point queries. This only pays of for many points, so the current $O(n^2)$ approach is still faster, but in general, this would be the way to go.

### My results

```
Measuring `poly_match_v1`
Took an avg of 223.03ms per iteration (14 iterations)
Measuring `poly_match_v1_5_vectorized`
Took an avg of 41.36ms per iteration (73 iterations)
Measuring `poly_match_v1_6_excessively_vectorized`
Took an avg of 10.04ms per iteration (299 iterations)
Measuring `poly_match_v1_7_numba`
Took an avg of 1.95ms per iteration (500 iterations)
Measuring `poly_match_v1_8_numba_early_exit`
Took an avg of 0.40ms per iteration (500 iterations)
Measuring `poly_match_v2_riir`
Took an avg of 562.50ms per iteration (6 iterations)
Measuring `poly_match_v3_riir_polygon`
Took an avg of 164.46ms per iteration (19 iterations)
Measuring `poly_match_v4_avoid_allocs`
Took an avg of 47.12ms per iteration (64 iterations)
Measuring `poly_match_v5_1_varied_polygons`
Took an avg of 3.19ms per iteration (500 iterations)
Measuring `poly_match_v5_find_all_in_rust`
Took an avg of 3.11ms per iteration (500 iterations)
```

For my own experiments, I tested polygons with different shape and varying number of vertices. I believe that this makes the test more realistic.

I could also update your experiments with the new polygons. It might change the performance numbers slightly.

polygons

### CODE REVIEW

**Comment by ohadravid** [comment]
Hi @99991 !

Those are very cool examples, the numba one esp.

I can't say that I completely follow everything that's going on, but: like I wrote in the original article, we aren't really doing "useful" work in this library, it is just a proxy to the original library's perf problems. 

Because of that, some of the optimizations don't really make sense: For example, a KD Tree won't work for the simple reason that both polygons and points change each time (again, just to maintain the analogy).

Similarly, doing extra computation per polygon before the actual search is "cheating" a bit, because (a) we have to include it when measuring the perf and (b) because it wasn't really possible in the original library (to clarify, analogous algorithmic improvements were used for the first stages of the 3D pipeline, but we still had the "list of objects with numpy attributes" problem when dealing with the results)

To me, I'd love to merge one or both of:

1. An example which is "as close as possible" to the original, but which uses numba with little algorithmic changes.
2. An example which "takes numpy to the limit", but which is clearly measuring the same thing (starting with just the list of polygons).

Of course, you can also keep this open PR as-is. It is interesting in it's own right :)

**Comment by 99991** [comment]
> Those are very cool examples, the numba one esp.

Thank you!

> Because of that, some of the optimizations don't really make sense: For example, a KD Tree won't work for the simple reason that both polygons and points change each time (again, just to maintain the analogy).

KDTrees can be built relatively quickly. It might still be worth it. Or perhaps not. I do not know the original task.

> we still had the "list of objects with numpy attributes" problem when dealing with the results

Copying the polygon data into a single NumPy array so that it can be worked on efficiently takes about 2 milliseconds. This means that a benchmark which includes this time is mostly measuring the overhead of an inefficient data layout. That is still a valid problem which might come up in practical applications, but I am not very interested in solving it.

**Comment by 99991** [comment]
I noticed that I am computing the distance to the closest vertex of the polygon instead of to the center, making my code about 5 times slower than it needed to be. I should probably have started with writing unit tests.

**Comment by ohadravid** [comment]
> This means that a benchmark which includes this time is mostly measuring the overhead of an inefficient data layout.

The article is essentially about converting an inefficient data layout in Python to a more efficient one in Rust, while keeping the same API 😉 

Part of the constraints of the system is that the previous steps produce this layout (mostly due to being very efficient at some other task), which means that we have to include any conversion costs when comparing results.

As I said, this is still a very interesting solution 🚀 , it's just that we can't directly compare the results.

**Comment by 99991** [comment]
> Part of the constraints of the system is that the previous steps produce this layout (mostly due to being very efficient at some other task)

I am fairly certain that this previous step could also be modified to use a contiguous memory layout, but it might be too much work.

**Comment by ohadravid** [comment]
BTW, I noticed that your `poly_match_v2_riir` is slower than the original Python version.
Perhphse you didn't use the `--release` flag when building using `maturin`?

My results on your branch are:
```
$ python ./measure_all.py
Measuring `poly_match_v1`
Took an avg of 295.71ms per iteration (11 iterations)
Measuring `poly_match_v1_5_vectorized`
Took an avg of 44.52ms per iteration (68 iterations)
Measuring `poly_match_v1_6_excessively_vectorized`
Took an avg of 9.17ms per iteration (328 iterations)
Measuring `poly_match_v1_7_numba`
Took an avg of 2.19ms per iteration (500 iterations)
Measuring `poly_match_v1_8_numba_early_exit`
Took an avg of 0.51ms per iteration (500 iterations)
Measuring `poly_match_v2_riir`
Took an avg of 26.49ms per iteration (114 iterations)
Measuring `poly_match_v3_riir_polygon`
Took an avg of 6.91ms per iteration (435 iterations)
Measuring `poly_match_v4_avoid_allocs`
Took an avg of 3.43ms per iteration (500 iterations)
Measuring `poly_match_v5_1_varied_polygons`
Took an avg of 1.05ms per iteration (500 iterations)
Measuring `poly_match_v5_find_all_in_rust`
Took an avg of 1.22ms per iteration (500 iterations)
```

**Comment by 99991** [comment]
You are right, I did not run it with the release flag. Perhaps build instructions would be helpful.

Here are the results with `--release`.

```
Measuring `poly_match_v1`
Took an avg of 225.51ms per iteration (14 iterations)
Measuring `poly_match_v1_5_vectorized`
Took an avg of 34.61ms per iteration (87 iterations)
Measuring `poly_match_v1_6_excessively_vectorized`
Took an avg of 7.63ms per iteration (394 iterations)
Measuring `poly_match_v1_7_numba`
Took an avg of 1.50ms per iteration (500 iterations)
Measuring `poly_match_v1_8_numba_early_exit`
Took an avg of 0.31ms per iteration (500 iterations)
Measuring `poly_match_v2_riir`
Took an avg of 20.56ms per iteration (146 iterations)
Measuring `poly_match_v3_riir_polygon`
Took an avg of 5.58ms per iteration (500 iterations)
Measuring `poly_match_v4_avoid_allocs`
Took an avg of 2.88ms per iteration (500 iterations)
Measuring `poly_match_v5_1_varied_polygons`
Took an avg of 0.89ms per iteration (500 iterations)
Measuring `poly_match_v5_find_all_in_rust`
Took an avg of 0.88ms per iteration (500 iterations)
```

**Pull request closed without merging**
