### PR TITLE
Implement full vectorization version

### PR DESCRIPTION
**Pull request by dangrie158**
Hi,
I stumbled upon the article on Lobste.rs today and just like #3 I also think the vectorisation approach isn't fairly represented. So I took the challenge and implemented a version that is fully vectorised using no loops at all, but tried to stay as close to the original API as possible.

I loved the article and really like the approaches to further optimise the simple implementation in rust, however I sadly wasn't able to build the project (something not available for arm64...). That's IMO the critical point  about this approach that you need to distribute the binaries for all platforms or expect everyone to have a rust toolchain installed. For a counter point about readability of the vectorised numpy code, I think this comes down to familiarity and I would love to get some feedback on my implementation regarding this aspect. For me, the code is still quite understandable as I tried to keep it much simpler than the code in #3 .

Anyways, I would love to get some feedback and more importantly I hope you get around to run my script on the same machine as all other implementations (since I'm not easily able to get the rust module working). On my machine I get a >100x speedup to the primitive baseline, so not quite what you achieved in rust 🤷 

Have a nice day,
Daniel

### CODE REVIEW

**Comment by ohadravid** [comment]
Hi! Thanks for taking the time and effort to put this version together! I'll look into it more deeply tomorrow, but it looks great.

Would you also mind sharing the compilation errors? I tested everything on x86 Linux and arm64 macOS so it should work 😅

**Comment by dangrie158** [comment]
Ah, nevermind.I got it compiling, there was some strange and long error message about missing libs due to some weirdness in my pyenv installation.

Here are the results including speedup. v4 and v5 still have a significant speedup compared to the pure vectorised version:

```
Measuring `poly_match_v1`
Took an avg of 128.94ms per iteration ( 24 iterations)   1.00x speedup
Measuring `poly_match_v1_5_vectorized`
Took an avg of  22.59ms per iteration (133 iterations)   5.71x speedup
Measuring `poly_match_v1_6_fully_vectorized`
Took an avg of   2.81ms per iteration (500 iterations)  45.93x speedup
Measuring `poly_match_v2_riir`
Took an avg of  20.69ms per iteration (146 iterations)   6.23x speedup
Measuring `poly_match_v3_riir_polygon`
Took an avg of   4.88ms per iteration (500 iterations)  26.42x speedup
Measuring `poly_match_v4_avoid_allocs`
Took an avg of   2.01ms per iteration (500 iterations)  64.14x speedup
Measuring `poly_match_v5_find_all_in_rust`
Took an avg of   0.63ms per iteration (500 iterations) 205.83x speedup
```

However the results on my hardware (M1 Pro) look somewhat different to yours so it would be interesting to get the results when the code runs on your machine :)

**Comment by ohadravid** [comment]
Awesome! The example is both simple, fast and well documented.
A very nice speedup 😎 

I'll merge this, and later today I'll run this on the same x86 linux I used for the original benchmark and update the table in the README.

Thanks again for working on this 🎉 

----

> strange and long error message about missing libs due to some weirdness in my pyenv installation.

Yes, there is definitely a lot more friction with building (and distributing) a mixed codebase. I hope to find the time to write a followup on how we do that (we moved from Docker+Poetry to Earthly+Poetry to Nix to Bazel).

> vectorisation approach isn't fairly represented

It's true, but I'll just add a note here: I had to cut it out of the article because it was already so long, but for the original library we also had to "group" (and regroup) objects in more complex ways, for example you can think of merging together a few close polygons to create a new "better" one. This, among other things, makes it a lot less viable to double down on numpy and it's vectorized operations.

**Review by ohadravid — APPROVED** [review]

**Comment by dangrie158** [comment]
> Awesome! The example is both simple, fast and well documented.

Thanks :) 
I was surprised there wasn't more to gain since I expected numpy to be heavily optimised to use vector extensions (as is visible in the flame graph) and your rust implementation is rather naive in that regard. 
I also tested to only work on the squared distance as you do in the rust implementation since `norm` is one of the big time hogs in the current implementation, but got even worse performance, probably because lumpy does something even smarter than just avoiding to calculate the square root 🤷‍♂️.

> Yes, there is definitely a lot more friction with building (and distributing) a mixed codebase. I hope to find the time to write a followup on how we do that (we moved from Docker+Poetry to Earthly+Poetry to Nix to Bazel).

That would be very interesting indeed since:

>  I had to cut it out of the article because it was already so long, but for the original library we also had to "group" (and regroup) objects in more complex ways

Yeah I experienced that in the past as well. Simple tasks can get quite tricky and always are on the risk of getting hard to read / maintain. So an explainer on how to manage external (rust) code would be really interesting for me.

Thanks for the merge, it was a fun challenge :)

**Pull request merged**
